name: Lint and SAST

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4 (pin)
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v4 (pin)
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest@sha256:12672acdb0949e19f9f6a4c2b288edd0b404f268f0ca7738a2c06f372f50362e
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4 (pin)
      - name: Semgrep scan
        run: semgrep scan --config p/javascript --config p/owasp-top-ten --error